#[Menus]
#  main = [
#      {Name = "Twitter", URL = "https://twitter.com/x41x4a/"},
#      {Name = "About", URL = "/about/"}
#  ]

baseURL = "https://securingthe.net"
title = "Securing The Net"
#themesDir = "../.."
theme = "m10c"
paginate = 10

[params]
  author = "AJ McQuay"
  description = "Tech ramblings from the desert"
  #[[params.social]]
  #  name = "github"
  #  url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/x41x4a"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"
